# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - PetSanctumAPI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://petsanctumserver.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0ada4504a4af47f79e7c7c9112643d2d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_bd21afacb8d947bd8c74c5cc9116718e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: petsanctumserver.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0ada4504a4af47f79e7c7c9112643d2d }}/node-docker-demo:${{ github.sha }}
        context: ./server
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PetSanctumAPI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7fa3b540e36640bfba03cf66993211fe }}
        images: 'petsanctumserver.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0ada4504a4af47f79e7c7c9112643d2d }}/node-docker-demo:${{ github.sha }}'
